apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-backend-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - artemmanko.duckdns.org
      secretName: python-backend-tls
  rules:
    - host: artemmanko.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-backend-service
                port:
                  number: 80